# scripts/pack_extension.ps1
# Packages the browser extension into a .crx file using Google Chrome.

$ErrorActionPreference = "Stop"

$workspaceRoot = Resolve-Path "$PSScriptRoot\.."
$extensionDir = Join-Path $workspaceRoot "extension"
$pemPath = Join-Path $workspaceRoot "extension.pem"
$crxTempPath = Join-Path $workspaceRoot "extension.crx"
$releasesDir = Join-Path $workspaceRoot "releases"
$crxDestPath = Join-Path $releasesDir "extension.crx"

# Ensure releases folder exists
if (-not (Test-Path $releasesDir)) {
    New-Item -ItemType Directory -Path $releasesDir | Out-Null
}

Write-Host "Searching for Google Chrome..." -ForegroundColor Cyan

# Define search paths for chrome.exe
$chromePaths = @(
    "C:\Program Files\Google\Chrome\Application\chrome.exe",
    "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    "$env:LocalAppData\Google\Chrome\Application\chrome.exe"
)

# Also check registry
$registryPaths = @(
    "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe",
    "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe"
)

$chromePath = $null

foreach ($regPath in $registryPaths) {
    if (Test-Path $regPath) {
        $val = (Get-ItemProperty -Path $regPath -Name "(default)" -ErrorAction SilentlyContinue)."(default)"
        if ($val -and (Test-Path $val)) {
            $chromePath = $val
            break
        }
    }
}

if (-not $chromePath) {
    foreach ($path in $chromePaths) {
        if (Test-Path $path) {
            $chromePath = $path
            break
        }
    }
}

if (-not $chromePath) {
    Write-Error "Google Chrome (chrome.exe) could not be found in standard installation paths or Registry. Chrome is required to pack the extension into a CRX file."
    exit 1
}

Write-Host "Found Chrome at: $chromePath" -ForegroundColor Green

# Build the command arguments
if (Test-Path $pemPath) {
    Write-Host "Found existing private key at: $pemPath" -ForegroundColor Yellow
    Write-Host "Packing extension using existing private key..." -ForegroundColor Cyan
    
    # Run chrome to pack
    Start-Process -FilePath $chromePath -ArgumentList "--pack-extension=`"$extensionDir`"", "--pack-extension-key=`"$pemPath`"" -Wait -NoNewWindow
}
else {
    Write-Host "No private key found at $pemPath. Chrome will generate a new private key." -ForegroundColor Yellow
    Write-Host "Packing extension and generating private key..." -ForegroundColor Cyan
    
    # Run chrome to pack (creates extension.crx and extension.pem in the parent directory)
    Start-Process -FilePath $chromePath -ArgumentList "--pack-extension=`"$extensionDir`"" -Wait -NoNewWindow
}

# Give Chrome a split second to finish disk write if async
Start-Sleep -Seconds 1

# Check if extension.crx was created
if (Test-Path $crxTempPath) {
    Write-Host "Successfully packaged CRX!" -ForegroundColor Green
    
    # Move CRX to releases directory
    Move-Item -Path $crxTempPath -Destination $crxDestPath -Force
    Write-Host "Moved CRX to: $crxDestPath" -ForegroundColor Green
    
    if (-not (Test-Path $pemPath)) {
        Write-Host "A new private key was generated by Chrome in the project root: $pemPath" -ForegroundColor Yellow
        Write-Host "Please KEEP this file safe to ensure subsequent packs use the same Extension ID!" -ForegroundColor Yellow
    }
}
else {
    Write-Error "Failed to generate CRX. Please check Chrome output or permissions."
    exit 1
}

Write-Host "Extension packaging completed successfully!" -ForegroundColor Green
